name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Docker image name
      id: meta
      run: |
        IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/meet
        TAG=latest
        echo "image=$IMAGE_NAME" >> $GITHUB_OUTPUT
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build . -f Dockerfile -t ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.tag }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.tag }}
